### ISSUE TITLE
Error in doc: useRelay doesn't support "host" argument

### ISSUE THREAD

**Issue by Extarys** [DeFUCC/gun-vue#11]
See the documentation [here](https://gun-vue.js.org/docs/composables/#userelay-host-%E2%87%92-relay):

![image](https://user-images.githubusercontent.com/11581433/156627571-7a342f6f-c3ca-497f-89f5-971fab173474.png)

And the `useRelay` function [here](https://github.com/DeFUCC/gun-vue/blob/65e62616bb2941813a724f939d25d685c577547c/composables/src/gun/useRelay.js#L74).

When I try to get the server's status, it always gives me the demo server:

`{ "peer": "https://etogun.glitch.me/gun", "host": "etogun.glitch.me", "status": "offline", "started": 0, "pulse": 0, "lag": 0, "diff": 0, "age": "0ms", "delay": 1646331513100, "blink": false }`

I'm still figuring everything out, with Nuxt 3 I finally was able to get something with your suggestion thanks!
```
const comp = shallowRef(null)

onMounted(() => {
  import('@gun-vue/composables').then(module => {
	  console.log(module)    
	  comp.value = module?.useRelay("http://localhost:4200/gun")
  })
})
```

**Comment by davay42** [comment]
If you want to use your relay, you need to set it like this:
```
import { useRelay } from '@gun-vue/composables'
const relay = useRelay()
relay.setPeer('http://0.0.0.0')
```

This save the url to the localstorage and reload the page, so you'll have all gun instances in sync with the new relay.
