### ISSUE TITLE
chats does not show the name if not ascii 

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#15]
#### It seems topic does not accept general utf-8 charactorsets

<img width="744" alt="image" src="https://user-images.githubusercontent.com/9952753/159190203-981c733a-da49-4e36-b4e2-838cc7d1bb31.png">

**Comment by davay42** [comment]
I use https://www.npmjs.com/package/slugify this lib to clean up the string and make it more consistent in the DB. Seems like it doesn't recognize Chinese...

**Comment by davay42** [comment]
Added a temporary workaround cae8bd1fd210d8f865b3d69b8928d8956fb531b2

**Comment by lospringliu** [comment]
fixed
