### ISSUE TITLE
which gun issue prevents using the latest release?

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#16]
feel that the latest release is stabler

**Comment by davay42** [comment]
<img width="478" alt="Снимок экрана 2022-03-22 в 23 32 55" src="https://user-images.githubusercontent.com/6184449/159570848-02f00dae-e588-4474-a4f7-a6804e9aebe3.png">

**Comment by davay42** [comment]
Played with some polyfills and yes, I've got the new Gun version running! Here's the hack d937829e53bf2c2d53e542212f63824c26b76e29

**Comment by lospringliu** [comment]
that is common issues that can be work arounded, I put below to index.html
```
    <script type="module">
      globalThis.global = globalThis
      import { Buffer } from "buffer"
      import process from "process"
      import EventEmitter from "events"
      globalThis.setImmediate = process.nextTick
      globalThis.process = process
      globalThis.Buffer = Buffer
      globalThis.EventEmitter = EventEmitter
    </script>
```

**Comment by lospringliu** [comment]
replace globalThis with window should get better compativility

**Comment by davay42** [comment]
I'll stick to this solution for now. It's located in `useGun.js`.

<img width="408" alt="Снимок экрана 2022-03-23 в 11 23 27" src="https://user-images.githubusercontent.com/6184449/159654995-bfdccb6d-1891-48f4-9769-1ccada2e38fe.png">

**Comment by philippedasilva-orizone** [comment]
Give: `document.setImmediate = setTimeoout`a try ;)
