### ISSUE TITLE
post displayed wrong on mobile browser

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#17]
- url `http://localhost:3000/?#/posts/`

- on desktop browser, it displays correct
```
<ul>
<li>v0.1</li>
<li>youtube 油管</li>
<li>ipfs</li>
<li>chat 聊天</li>
<li>post 文章</li>
<li>private chat 私聊</li>
<li>decentralize 去中心化</li>
</ul>
```
<img width="436" alt="image" src="https://user-images.githubusercontent.com/9952753/159819051-3a0f9958-2f5a-4063-a45f-296091bd602b.png">

- on mobile, it displays incorrect, with base64 codes, seems like missing a tranform step
<img width="476" alt="image" src="https://user-images.githubusercontent.com/9952753/159818993-3ba2f27c-02be-40a0-838b-c61e5b2db111.png">

**Comment by lospringliu** [comment]
probably now a real issue, I created one from gun-vue.js.org and it displays correct

**Comment by davay42** [comment]
The glitch relay is down and I can't figure out the error that made it crush. So I've integrated the Volunteer DHT functionality to change the Gun relay peer used for data syncing. Hope that helps! Try the v.0.7.8

**Comment by lospringliu** [comment]
strange the issue is gone

but I remember to see this before. will keep an eye on it

**Comment by lospringliu** [comment]
if you use node v16, I do it like this
```javascript
import("@gun-vue/relay").then(mod => 
  mod.default.init({
    host: "relay.bcapps.ca",
    path: "public"
  })
)
```
