### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mehotkhan** [DeFUCC/gun-vue#2]
on build i got this err 

`Could not resolve './Account/Profile.vue' from src/index.js`

it seems on last update after change some file name , some code don't update correctly but on commit 
`aaa41ae0a585cd271872c44ce905267a2ce56c84` , code works correctly

**Comment by davay42** [comment]
The project is in active development and full of bugs ) But now it builds just fine for me. Try the latest commit version.

**Comment by mehotkhan** [comment]
im also working in vue+gun , i know your code in in development :)
look in this path : `gun-vue/components/src/index.js`
EX : `export { default as AccountProfile } from "./Account/Profile.vue";`

the folder name is Capital but main folder not Capital :)
I'm also work in linux

**Comment by davay42** [comment]
<img width="502" alt="Снимок экрана 2022-01-16 в 20 31 01" src="https://user-images.githubusercontent.com/6184449/149671002-034a3eeb-f82b-4420-b544-51dac761502d.png">

Looks fine now. Try to pull the latest changes, the folder names should be matching.
Are you on windows? Are you using pnpm for the workspace?

**Comment by mehotkhan** [comment]
im on linux , and test with pnpm 
fetch full repo again and same err 
`
> @gun-vue/components@0.5.5 build /home/ali/Projects/gun-vue/components
> vite build

vite v2.7.12 building for production...
✓ 1 modules transformed.
Could not resolve './Account/Profile.vue' from src/index.js
error during build:
Error: Could not resolve './Account/Profile.vue' from src/index.js
    at error (/home/ali/Projects/gun-vue/node_modules/.pnpm/rollup@2.60.1/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/home/ali/Projects/gun-vue/node_modules/.pnpm/rollup@2.60.1/node_modules/rollup/dist/shared/rollup.js:22345:24)
    at /home/ali/Projects/gun-vue/node_modules/.pnpm/rollup@2.60.1/node_modules/rollup/dist/shared/rollup.js:22319:26
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

`

![image](https://user-images.githubusercontent.com/6389743/149722919-221808d8-42d1-467f-88ac-69edf44dab48.png)

**Comment by davay42** [comment]
So your system makes the repo folder names lowercase... Should I rename folders to lowercase in the project to make it more stable on Linux systems?

**Comment by mehotkhan** [comment]
some Typo need updates ,
I create merge request 
https://github.com/DeFUCC/gun-vue/pull/3

**Comment by davay42** [comment]
All folders are lowercase now. The components' names begin with an uppercase letter as a convention for Vue.
