### ISSUE TITLE
Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by jilv220** [DeFUCC/gun-vue#22]

**Comment by davay42** [comment]
Hmm, strange. Are you on recent version? What system are you running it on?

**Comment by jilv220** [comment]
Arch.  Node 16.15.0.  yarn 1.22.19

**Comment by davay42** [comment]
@jilv220 It's hard for me to debug Linux setups. Any ideas what could go wrong? )

**Comment by drunkod** [comment]
> 

Maybe try install in docker or codespaces.

**Comment by davay42** [comment]
Should be resolved by v.0.12.x. Try it. Open a new issue if the error is still present.
