### ISSUE TITLE
Error from default install from yarn 

### ISSUE THREAD

**Issue by drunkod** [DeFUCC/gun-vue#23]
[plugin:vite:vue] v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.
/workspaces/gun-vue/components/src/post/reaction/PostReactionButton.vue:39:408

**Comment by davay42** [comment]
Yes, I've seen this coming. It's the new version of vite-plugin-vue being more involved 😅 I'll catch these v-models.

**Comment by davay42** [comment]
Closed #96c6bdf1bb047878938ebcb38cd0d5a3b9e7eb2d

**Comment by davay42** [comment]
https://github.com/DeFUCC/gun-vue/commit/96c6bdf1bb047878938ebcb38cd0d5a3b9e7eb2d
