### ISSUE TITLE
Error in Nuxt 3

### ISSUE THREAD

**Issue by drunkod** [DeFUCC/gun-vue#24]
import { gunAvatar, useColor, useGun, useUser } from '@gun-vue/composables'

Error:
Named export 'mountElement' not found. The requested module './vendor.es.js' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from './vendor.es.js'; const { SEA: Sa, gunAvatar: ka, mountClass: ja, mountElement: Aa, ms: Pa, slugify: Oa } = pkg;

[Vue warn]: Unhandled error during execution of setup function                                                
  at <Anonymous key="default" name="default" hasTransition=false >

**Comment by davay42** [comment]
Try updating the package to v.0.11.6. I've changed it to `type: module` and it should work just fine!

**Comment by davay42** [comment]
And yes, the package is still client-side only and it may throw errors while building for SSR. The way to deal with it is this:

1. make your component async
```js
const { useColor } = await import('@gun-vue/composables')
```

2. Make it load only on client side
```html
	<client-only>
		<Suspense>
			<your-component></your-component>
		</Suspense>
	</client-only>
```

This prevents any code running during ssr build and while making it available in the browser.

**Comment by drunkod** [comment]
> And yes, the package is still client-side only and it may throw errors while building for SSR. The way to deal with it is this:
> 
> 1. make your component async
> 
> ```js
> const { useColor } = await import('@gun-vue/composables')
> ```
> 
> 2. Make it load only on client side
> 
> ```
> 	<client-only>
> 		<Suspense>
> 			<your-component></your-component>
> 		</Suspense>
> 	</client-only>
> ```
> 
> This prevents any code running during ssr build and while making it available in the browser.

Thanks.


I try:
import { RoomButton } from '@gun-vue/components'
const { RoomButton } = await import('@gun-vue/components')

New error with components :

[vite] Internal server error: Failed to resolve entry for package "@gun-vue/components". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /workspaces/gun-nuxt-starter/src/components/NavBar.client.vue

**Comment by davay42** [comment]
What version of @gun-vue you're on? Please try the recent **v.0.11.7**, hope it's fixed now :)

**Comment by drunkod** [comment]
I try from example :https://gun-vue.js.org/components/#/story/src-docs-components-story-js

[https://stackblitz.com/edit/github-2nlvnm?file=pages%2Fchat.vue](https://stackblitz.com/edit/github-2nlvnm?file=pages%2Fchat.vue)



<script setup lang="ts">
import { ChatRoom } from '@gun-vue/components'
</script>

<template>
    <div>
      ChatRoom
      <client-only><ChatRoom /></client-only>
      
    </div>
  </template>
  
    "dependencies": {
    "@gun-vue/components": "^0.11.7"
  }
  
Error:
[plugin:vite:import-analysis] Failed to resolve entry for package "@gun-vue/components". The package may have incorrect main/module/exports specified in its package.json.
/home/projects/github-2nlvnm/pages/chat.vue

  
  

> What version of @gun-vue you're on? Please try the recent **v.0.11.7**, hope it's fixed now :)

**Comment by davay42** [comment]
Using Gun-Vue in a SSR environment doesn't make sense as it's a real time reactive database and dealing with it during build process is a very complicated topic. If you need to mount these reactive components into your Nuxt project, you should be sure to use it asynchronously with `const { ChatRoom } = await import('@gun-vue/components')` and use it with Suspense tag. 

BTW: I've fixed the exports of the package, yet it seems to still have some errors in the build. I'll debug it later. Please try v. 0.11.8 with a client side Vue code to verify if it works for you.

**Comment by davay42** [comment]
I've fixed all the minor bugs preventing the use of the components as a package. Now the v.0.12.0 should load correctly. You'll need to load the components async to get them working. It's quite easy with Vue.
