### ISSUE TITLE
Error in Vue 3 Vite template

### ISSUE THREAD

**Issue by drunkod** [DeFUCC/gun-vue#25]
add in main.js
import { GunVuePlugin } from '@gun-vue/components'

and if add in ./router.js
import { RoomList, AccountHome } from '@gun-vue/components'

Error: Uncaught TypeError: Cannot read properties of undefined (reading 'unescapeAll')
    at ink.es.js:59:12

**Comment by davay42** [comment]
Yes, there was a bug with manual chunking for the builds - the order of the imports was incorrect. Now all the JS code is delivered in one solid chunk and is much more portable and reliable. Please, move on to [v.0.12.0](https://www.npmjs.com/package/@gun-vue/components) for the fix.
