### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by drunkod** [DeFUCC/gun-vue#27]
"Failed to resolve component: fad-random-1dice
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. "

exmple:
https://stackblitz.com/edit/vitejs-vite-5vqaku?file=src/components/HelloWorld.vue

**Comment by davay42** [comment]
Yeah, a couple of icons left unchanged after moving from `unplugin-components` svgs to `unocss` class-based icons. Fixed it in v.0.12.4. Demo: https://stackblitz.com/edit/vitejs-vite-kgvgph?file=package.json
