### ISSUE TITLE
looks like some problem when navigate to the `space` route from homepage

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#30]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9952753/215569292-b7aa939e-f24b-4c79-b84a-735d2da81df0.png">

**Comment by davay42** [comment]
Hmm. Can't reproduce the error in my browser. Try pulling the latest version. We are in the middle of typescript conversion, so there may be some hiccups. But we're moving! 🚀

**Comment by lospringliu** [comment]
thanks. I checked again but it is good now after cleaning up the storage.

Possible because I have another repo using the same storage (and dev port) but did not clear storage before
