### ISSUE TITLE
routing to space page may get error upon first visit, likey from composable useDraw

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#32]
## reproduce
1. visit https://gun-vue.js.org/
2. do a full page refresh
3. cliek `Space`

## screenshot
<img width="900" alt="image" src="https://user-images.githubusercontent.com/9952753/217044236-93ac67c8-f048-4770-b612-5f060d31a6f2.png">

**Comment by davay42** [comment]
This seems to happen only after returning to a root room from a nested room. Seems like the components got updated with :key="route.path" and the target elements are not ready to get mounted - hence the errors from the `drauu` lib and my SVGMouse adapter that mounts to an SVG.

This needs a deep debugging on multiple layers. Let's see if we can do it at this stage. Or may be just reload the page after changing the room for now? %)

**Comment by lospringliu** [comment]
yes, likely because it is a new room and only one user is there.
