### ISSUE TITLE
what about dark theme support?

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#35]
current rendering does not seem to fit dark mode well.

What about make some global update to make it work with something like https://anu-vue.netlify.app/guide/features/theme.html ?
this does not require to set configurations on a lot of places

**Comment by lospringliu** [comment]
light them
<img width="710" alt="image" src="https://user-images.githubusercontent.com/9952753/222283122-8d368908-cb1b-4c8b-a1f0-4ffec74aa2ca.png">

**Comment by lospringliu** [comment]
dark theme
<img width="683" alt="image" src="https://user-images.githubusercontent.com/9952753/222283219-61bdb952-3c3b-4cd2-99ad-a2ff02275dcc.png">

**Comment by lospringliu** [comment]
not a real issue as the configuration will show the same effect by default for both dark and regular theme. It would be good to make it responds to common dark theme though

**Comment by davay42** [comment]
Yeah, this feature is very needed, but I postponed it not to waste too much time on refining the visual part, focusing on the db and build system. We can sprinkle some "dark-..." classes everywhere to have the dark mode feature, but may be there's another way. I'm thinking of implementing some kind of theming. May be you got good examples for that too? 😄

**Comment by davay42** [comment]
Actually Anu seems to be a nice case! It uses the UnoCSS plugin system, which seems to be perfect for GunVue too. Need to explore this more. May be even integrate Anu as an underlying suitcase of basic components.

**Comment by lospringliu** [comment]
Anu has dark theme support by default and do not need to add `dark-` classes everywhere, but likely will not have your ideal  visual expectations

**Comment by lospringliu** [comment]
I played half day with `anu`, it feels to be a good ui library, perhaps you can think of integrating it to gun-vue

**Comment by davay42** [comment]
Yeah! I'm just exploring it's docs and source to find ways to integrate into the components package. And still make them customizable. If you have a clue how to do it - please share )

**Comment by davay42** [comment]
Man, I just can't make it work with my current layered setup... How to manage styles not to be in need to build the components each time I need to check them in the app.

**Comment by lospringliu** [comment]
current version is a bit old (0.12.0), they have `edge` builds let me see if I can make it to work with your repo

**Comment by lospringliu** [comment]
I found need some options like below, it seems to be very flexible
```vue
      <ASelect optionsWrapperClasses="z-500"/>
      <AInput type="number" input-wrapper-classes="px-0" />
```

**Comment by davay42** [comment]
Seems doable! Like so we need a prop of classes for each wrapper in a component. And so the initial classes can be stored in props default. But idk how UnoCSS handles that. Will see 👀

**Comment by lospringliu** [comment]
markdown with light/dark
```
   // https://github.com/antfu/vite-plugin-vue-markdown
    // Don't need this? Try vitesse-lite: https://github.com/antfu/vitesse-lite
    Markdown({
      wrapperClasses: 'prose prose-sm m-auto text-left',
      headEnabled: true,
      markdownItSetup(md) {
        // https://prismjs.com/
        md.use(Shiki, {
          theme: {
            light: 'vitesse-light',
            dark: 'vitesse-dark',
          },
        })
        md.use(LinkAttributes, {
          matcher: (link: string) => /^https?:\/\//.test(link),
          attrs: {
            target: '_blank',
            rel: 'noopener',
          },
        }) 
      },
    }),

```

**Comment by lospringliu** [comment]
I found it easy to work with anu by default if you do not set background color, or if you set a neutral color like `gray`

**Comment by lospringliu** [comment]
your gun-avatar seems to support `dark`, is it convenient to update `useBackgroud` to honor?

**Comment by lospringliu** [comment]
#37

**Comment by davay42** [comment]
Good point! Yet in my experience it's better to have one isDark instance established somewhere and imported from all the places. I'll test your solution too.

**Comment by lospringliu** [comment]
yes, expose from your ui composable is better

**Comment by davay42** [comment]
@lospringliu I've got you covered! Full dark mode support has landed with v.0.14.2!
