### ISSUE TITLE
what does this message mean from console?

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#9]
chain not yet supported for {enc: 'SEA{"ct":"is2z6z0RDGYjstwQplGGul8BJGOZ1BeHaFhX2gl6…","iv":"Ic1uc5AoXm44qdY3pMCC","s":"UYS9JROLHxAt"}', features: 'SEA{"m":{"c":"jFjrmOEaRy-GAJlOCdG4SGoaLm_4AGMPP1sf…E/N+HKvZc7BUd3g6167A/GntJm4WCluI8VYF+G1Cjqnhg=="}', hosts: 'SEA{"m":{"c":"jFjrmOEaRy-GAJlOCdG4SGoaLm_4AGMPP1sf…57dvwcxxMgDZIEUwXXULtzmyt0/2pL4I/LgByoiB3WFRQ=="}', profile: 'SEA{"m":{"c":"jFjrmOEaRy-GAJlOCdG4SGoaLm_4AGMPP1sf…vELmFwmf241pdP/0mERYE+h90wXsXjYu7alNNQgfDzvXg=="}'}

**Comment by davay42** [comment]
That's mystery for me too 😅

**Comment by davay42** [comment]
Seems not to appear any more with the newer Gun version.
